// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CompleteActionReducer from "../complete_action_reducer";
import DeleteActionReducer from "../delete_action_reducer";
import DeleteCardReducer from "../delete_card_reducer";
import DeletePlayerReducer from "../delete_player_reducer";
import DeleteZoneReducer from "../delete_zone_reducer";
import DeleteZoneAtReducer from "../delete_zone_at_reducer";
import FillZoneReducer from "../fill_zone_reducer";
import FillZoneAtReducer from "../fill_zone_at_reducer";
import QueueActionReducer from "../queue_action_reducer";
import SetCardFlagsReducer from "../set_card_flags_reducer";
import SetZoneRowReducer from "../set_zone_row_reducer";
import SetZoneRowAtReducer from "../set_zone_row_at_reducer";
import SetZoneTileReducer from "../set_zone_tile_reducer";
import SetZoneTileAtReducer from "../set_zone_tile_at_reducer";
import StartActionReducer from "../start_action_reducer";
import UpdateCardLinkReducer from "../update_card_link_reducer";
import UpdateCardLocationReducer from "../update_card_location_reducer";
import UpsertCardReducer from "../upsert_card_reducer";
import UpsertPlayerReducer from "../upsert_player_reducer";
import UpsertZoneReducer from "../upsert_zone_reducer";
import UpsertZoneAtReducer from "../upsert_zone_at_reducer";

export type CompleteActionParams = __Infer<typeof CompleteActionReducer>;
export type DeleteActionParams = __Infer<typeof DeleteActionReducer>;
export type DeleteCardParams = __Infer<typeof DeleteCardReducer>;
export type DeletePlayerParams = __Infer<typeof DeletePlayerReducer>;
export type DeleteZoneParams = __Infer<typeof DeleteZoneReducer>;
export type DeleteZoneAtParams = __Infer<typeof DeleteZoneAtReducer>;
export type FillZoneParams = __Infer<typeof FillZoneReducer>;
export type FillZoneAtParams = __Infer<typeof FillZoneAtReducer>;
export type QueueActionParams = __Infer<typeof QueueActionReducer>;
export type SetCardFlagsParams = __Infer<typeof SetCardFlagsReducer>;
export type SetZoneRowParams = __Infer<typeof SetZoneRowReducer>;
export type SetZoneRowAtParams = __Infer<typeof SetZoneRowAtReducer>;
export type SetZoneTileParams = __Infer<typeof SetZoneTileReducer>;
export type SetZoneTileAtParams = __Infer<typeof SetZoneTileAtReducer>;
export type StartActionParams = __Infer<typeof StartActionReducer>;
export type UpdateCardLinkParams = __Infer<typeof UpdateCardLinkReducer>;
export type UpdateCardLocationParams = __Infer<typeof UpdateCardLocationReducer>;
export type UpsertCardParams = __Infer<typeof UpsertCardReducer>;
export type UpsertPlayerParams = __Infer<typeof UpsertPlayerReducer>;
export type UpsertZoneParams = __Infer<typeof UpsertZoneReducer>;
export type UpsertZoneAtParams = __Infer<typeof UpsertZoneAtReducer>;

