// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AttachTechniqueToEventTileReducer from "../attach_technique_to_event_tile_reducer";
import AttachTechniqueToWorldTileReducer from "../attach_technique_to_world_tile_reducer";
import BootstrapMinimalWorldReducer from "../bootstrap_minimal_world_reducer";
import DetachTechniqueFromHostReducer from "../detach_technique_from_host_reducer";
import QueueRecipeOnHostReducer from "../queue_recipe_on_host_reducer";

export type AttachTechniqueToEventTileParams = __Infer<typeof AttachTechniqueToEventTileReducer>;
export type AttachTechniqueToWorldTileParams = __Infer<typeof AttachTechniqueToWorldTileReducer>;
export type BootstrapMinimalWorldParams = __Infer<typeof BootstrapMinimalWorldReducer>;
export type DetachTechniqueFromHostParams = __Infer<typeof DetachTechniqueFromHostReducer>;
export type QueueRecipeOnHostParams = __Infer<typeof QueueRecipeOnHostReducer>;

