// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddCardBitsReducer from "../add_card_bits_reducer";
import BootstrapReducer from "../bootstrap_reducer";
import CreateCardReducer from "../create_card_reducer";
import CreatePlayerReducer from "../create_player_reducer";
import DeleteActionTrackerReducer from "../delete_action_tracker_reducer";
import DeleteCardReducer from "../delete_card_reducer";
import DeleteCardLinkReducer from "../delete_card_link_reducer";
import DeleteCardPositionReducer from "../delete_card_position_reducer";
import DeleteCardStateReducer from "../delete_card_state_reducer";
import DeleteCardVarReducer from "../delete_card_var_reducer";
import DeletePlayerReducer from "../delete_player_reducer";
import DeleteSoulAlignmentReducer from "../delete_soul_alignment_reducer";
import RemoveCardBitsReducer from "../remove_card_bits_reducer";
import SetCardBitsReducer from "../set_card_bits_reducer";
import SetCardStateReducer from "../set_card_state_reducer";
import SetCardVarReducer from "../set_card_var_reducer";
import UpdateActionQueueTimesReducer from "../update_action_queue_times_reducer";
import UpdateActionRecipeReducer from "../update_action_recipe_reducer";
import UpdateCardReducer from "../update_card_reducer";
import UpdatePlayerCardReducer from "../update_player_card_reducer";
import UpsertActionTrackerReducer from "../upsert_action_tracker_reducer";
import UpsertCardLinkReducer from "../upsert_card_link_reducer";
import UpsertCardPositionReducer from "../upsert_card_position_reducer";
import UpsertSoulAlignmentReducer from "../upsert_soul_alignment_reducer";

export type AddCardBitsParams = __Infer<typeof AddCardBitsReducer>;
export type BootstrapParams = __Infer<typeof BootstrapReducer>;
export type CreateCardParams = __Infer<typeof CreateCardReducer>;
export type CreatePlayerParams = __Infer<typeof CreatePlayerReducer>;
export type DeleteActionTrackerParams = __Infer<typeof DeleteActionTrackerReducer>;
export type DeleteCardParams = __Infer<typeof DeleteCardReducer>;
export type DeleteCardLinkParams = __Infer<typeof DeleteCardLinkReducer>;
export type DeleteCardPositionParams = __Infer<typeof DeleteCardPositionReducer>;
export type DeleteCardStateParams = __Infer<typeof DeleteCardStateReducer>;
export type DeleteCardVarParams = __Infer<typeof DeleteCardVarReducer>;
export type DeletePlayerParams = __Infer<typeof DeletePlayerReducer>;
export type DeleteSoulAlignmentParams = __Infer<typeof DeleteSoulAlignmentReducer>;
export type RemoveCardBitsParams = __Infer<typeof RemoveCardBitsReducer>;
export type SetCardBitsParams = __Infer<typeof SetCardBitsReducer>;
export type SetCardStateParams = __Infer<typeof SetCardStateReducer>;
export type SetCardVarParams = __Infer<typeof SetCardVarReducer>;
export type UpdateActionQueueTimesParams = __Infer<typeof UpdateActionQueueTimesReducer>;
export type UpdateActionRecipeParams = __Infer<typeof UpdateActionRecipeReducer>;
export type UpdateCardParams = __Infer<typeof UpdateCardReducer>;
export type UpdatePlayerCardParams = __Infer<typeof UpdatePlayerCardReducer>;
export type UpsertActionTrackerParams = __Infer<typeof UpsertActionTrackerReducer>;
export type UpsertCardLinkParams = __Infer<typeof UpsertCardLinkReducer>;
export type UpsertCardPositionParams = __Infer<typeof UpsertCardPositionReducer>;
export type UpsertSoulAlignmentParams = __Infer<typeof UpsertSoulAlignmentReducer>;

