// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  cardId: __t.u32().primaryKey().name("card_id"),
  recipeDefinitionId: __t.u16().name("recipe_definition_id"),
  recipeLock: __t.bool().name("recipe_lock"),
  magneticInputs: __t.string().name("magnetic_inputs"),
  queuedAt: __t.i64().name("queued_at"),
  startedAt: __t.i64().name("started_at"),
  completedAt: __t.i64().name("completed_at"),
});
