// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  CardKind,
} from "./types";


export default __t.row({
  cardId: __t.u64().primaryKey().name("card_id"),
  soulId: __t.u64().name("soul_id"),
  get kind() {
    return CardKind;
  },
  name: __t.string(),
  bgColor: __t.option(__t.string()).name("bg_color"),
  linkedSoulId: __t.option(__t.u64()).name("linked_soul_id"),
});
