// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  t as __t,
} from "spacetimedb";

export default __t.row({
  cardId: __t.u64().primaryKey().name("card_id"),
  soulId: __t.u64().name("soul_id"),
  definitionId: __t.u32().name("definition_id"),
  linkedSoulId: __t.option(__t.u64()).name("linked_soul_id"),
});
