// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  TileHostType,
} from "./types";

export default {
  actorSoulId: __t.u64(),
  get hostType() {
    return TileHostType;
  },
  hostId: __t.u64(),
  recipeId: __t.u32(),
  techniqueCardId: __t.u64(),
  inputCardIds: __t.array(__t.u64()),
};
