// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  t as __t,
} from "spacetimedb";

import {
  RecipeQueueState,
  TileHostType,
} from "./types";

export default __t.row({
  queueId: __t.u64().primaryKey().name("queue_id"),
  recipeId: __t.u32().name("recipe_id"),
  actorSoulId: __t.u64().name("actor_soul_id"),
  get hostType() {
    return TileHostType;
  },
  hostId: __t.u64().name("host_id"),
  queuedAtUnixMs: __t.u64().name("queued_at_unix_ms"),
  startedAtUnixMs: __t.option(__t.u64()).name("started_at_unix_ms"),
  get state() {
    return RecipeQueueState;
  },
});
