// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  TileHostType,
  RecipeQueueState,
} from "./types";


export default __t.row({
  queueId: __t.u64().primaryKey().name("queue_id"),
  recipeId: __t.u32().name("recipe_id"),
  actorSoulId: __t.u64().name("actor_soul_id"),
  get hostType() {
    return TileHostType.name("host_type");
  },
  hostId: __t.u64().name("host_id"),
  queuedAtUnixMs: __t.u64().name("queued_at_unix_ms"),
  startedAtUnixMs: __t.option(__t.u64()).name("started_at_unix_ms"),
  get state() {
    return RecipeQueueState;
  },
});
