// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  t as __t,
} from "spacetimedb";

export default __t.row({
  queueCardId: __t.u64().primaryKey().name("queue_card_id"),
  queueId: __t.u64().name("queue_id"),
  cardId: __t.u64().name("card_id"),
});
