// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  SubordinateType,
} from "./types";


export default __t.row({
  soulId: __t.u64().primaryKey().name("soul_id"),
  name: __t.string(),
  playerId: __t.option(__t.identity()).name("player_id"),
  ownerSoulId: __t.option(__t.u64()).name("owner_soul_id"),
  get subordinateType() {
    return __t.option(SubordinateType).name("subordinate_type");
  },
});
