// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  TileHostType,
} from "./types";


export default __t.row({
  attachmentId: __t.u64().primaryKey().name("attachment_id"),
  soulId: __t.u64().name("soul_id"),
  get hostType() {
    return TileHostType.name("host_type");
  },
  hostId: __t.u64().name("host_id"),
  techniqueCardId: __t.u64().name("technique_card_id"),
});
