// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ActionTracker = __t.object("ActionTracker", {
  cardId: __t.u32(),
  recipeDefinitionId: __t.u16(),
  recipeLock: __t.bool(),
  magneticInputs: __t.string(),
  queuedAt: __t.i64(),
  startedAt: __t.i64(),
  completedAt: __t.i64(),
});
export type ActionTracker = __Infer<typeof ActionTracker>;

export const Card = __t.object("Card", {
  cardId: __t.u32(),
  definitionId: __t.u16(),
  cardType: __t.u16(),
  ownerCardId: __t.u32(),
});
export type Card = __Infer<typeof Card>;

export const CardState = __t.object("CardState", {
  cardId: __t.u32(),
  status: __t.u64(),
  flags: __t.u64(),
});
export type CardState = __Infer<typeof CardState>;

export const CardTracker = __t.object("CardTracker", {
  cardId: __t.u32(),
  linkedCardId: __t.u32(),
  q: __t.i32(),
  r: __t.i32(),
  z: __t.i32(),
});
export type CardTracker = __Infer<typeof CardTracker>;

export const CardVar = __t.object("CardVar", {
  id: __t.u64(),
  cardId: __t.u32(),
  name: __t.string(),
  value: __t.string(),
});
export type CardVar = __Infer<typeof CardVar>;

export const EventTracker = __t.object("EventTracker", {
  tileId: __t.u32(),
  cardId: __t.u32(),
  createTime: __t.i64(),
});
export type EventTracker = __Infer<typeof EventTracker>;

export const Player = __t.object("Player", {
  playerId: __t.u32(),
  cardId: __t.u32(),
});
export type Player = __Infer<typeof Player>;

export const SlotTracker = __t.object("SlotTracker", {
  tileId: __t.u32(),
  cardId: __t.u32(),
  q: __t.i32(),
  r: __t.i32(),
});
export type SlotTracker = __Infer<typeof SlotTracker>;

export const SoulAlignment = __t.object("SoulAlignment", {
  cardId: __t.u32(),
  factionId: __t.u32(),
  groupId: __t.u32(),
  permissions: __t.u64(),
});
export type SoulAlignment = __Infer<typeof SoulAlignment>;

export const TileState = __t.object("TileState", {
  tileId: __t.u32(),
  status: __t.u64(),
  flags: __t.u64(),
});
export type TileState = __Infer<typeof TileState>;

export const TileVar = __t.object("TileVar", {
  id: __t.u64(),
  tileId: __t.u32(),
  name: __t.string(),
  value: __t.string(),
});
export type TileVar = __Infer<typeof TileVar>;

