// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Action = __t.object("Action", {
  cardId: __t.u32(),
  recipe: __t.u16(),
  start: __t.u32(),
  end: __t.u32(),
  flags: __t.u8(),
  zone: __t.u32(),
  position: __t.u8(),
});
export type Action = __Infer<typeof Action>;

export const Card = __t.object("Card", {
  cardId: __t.u32(),
  definition: __t.u16(),
  link: __t.u32(),
  flags: __t.u64(),
  zone: __t.u32(),
  position: __t.u8(),
});
export type Card = __Infer<typeof Card>;

export const Player = __t.object("Player", {
  playerId: __t.u32(),
  name: __t.string(),
  cardId: __t.u32(),
  zone: __t.u32(),
  position: __t.u8(),
});
export type Player = __Infer<typeof Player>;

export const Zone = __t.object("Zone", {
  zone: __t.u32(),
  t0: __t.u64(),
  t1: __t.u64(),
  t2: __t.u64(),
  t3: __t.u64(),
  t4: __t.u64(),
  t5: __t.u64(),
  t6: __t.u64(),
  t7: __t.u64(),
});
export type Zone = __Infer<typeof Zone>;

