// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Card = __t.object("Card", {
  cardId: __t.u64(),
  soulId: __t.u64(),
  get kind() {
    return CardKind;
  },
  name: __t.string(),
  bgColor: __t.option(__t.string()),
  linkedSoulId: __t.option(__t.u64()),
});
export type Card = __Infer<typeof Card>;

// The tagged union or sum type for the algebraic type `CardKind`.
export const CardKind = __t.enum("CardKind", {
  Technique: __t.unit(),
  Essence: __t.unit(),
  Sundries: __t.unit(),
  Reveries: __t.unit(),
  Soul: __t.unit(),
});
export type CardKind = __Infer<typeof CardKind>;

export const EventTile = __t.object("EventTile", {
  eventTileId: __t.u64(),
  soulId: __t.u64(),
  name: __t.string(),
  displayOrder: __t.u32(),
});
export type EventTile = __Infer<typeof EventTile>;

export const Soul = __t.object("Soul", {
  soulId: __t.u64(),
  name: __t.string(),
  playerId: __t.option(__t.identity()),
  ownerSoulId: __t.option(__t.u64()),
  get subordinateType() {
    return __t.option(SubordinateType);
  },
});
export type Soul = __Infer<typeof Soul>;

// The tagged union or sum type for the algebraic type `SubordinateType`.
export const SubordinateType = __t.enum("SubordinateType", {
  Control: __t.unit(),
  Influence: __t.unit(),
  Observe: __t.unit(),
});
export type SubordinateType = __Infer<typeof SubordinateType>;

// The tagged union or sum type for the algebraic type `TileHostType`.
export const TileHostType = __t.enum("TileHostType", {
  WorldTile: __t.unit(),
  EventTile: __t.unit(),
});
export type TileHostType = __Infer<typeof TileHostType>;

export const TileStageEntry = __t.object("TileStageEntry", {
  stageEntryId: __t.u64(),
  soulId: __t.u64(),
  get hostType() {
    return TileHostType;
  },
  hostId: __t.u64(),
  cardId: __t.u64(),
  orderIndex: __t.u32(),
});
export type TileStageEntry = __Infer<typeof TileStageEntry>;

export const TileTechniqueAttachment = __t.object("TileTechniqueAttachment", {
  attachmentId: __t.u64(),
  soulId: __t.u64(),
  get hostType() {
    return TileHostType;
  },
  hostId: __t.u64(),
  techniqueCardId: __t.u64(),
});
export type TileTechniqueAttachment = __Infer<typeof TileTechniqueAttachment>;

export const WorldTile = __t.object("WorldTile", {
  tileId: __t.u64(),
  name: __t.string(),
  q: __t.i32(),
  r: __t.i32(),
});
export type WorldTile = __Infer<typeof WorldTile>;

