// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  zone: __t.u32(),
  t0: __t.u64(),
  t1: __t.u64(),
  t2: __t.u64(),
  t3: __t.u64(),
  t4: __t.u64(),
  t5: __t.u64(),
  t6: __t.u64(),
  t7: __t.u64(),
};
