// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  t as __t,
} from "spacetimedb";

export default __t.row({
  tileId: __t.u64().primaryKey().name("tile_id"),
  definitionId: __t.u32().name("definition_id"),
  q: __t.i32(),
  r: __t.i32(),
});
